// Downloads character icons from the game-icons repo, saves the raw SVGs
// to assets/icons/, and generates js/icons.js with embedded path data.
import { writeFile, mkdir } from "node:fs/promises";

const ICONS = {
  frodo:    ["delapouite/power-ring",  "Delapouite", "Power ring"],
  sam:      ["delapouite/watering-can","Delapouite", "Watering can"],
  merry:    ["lorc/hunting-horn",      "Lorc",       "Hunting horn"],
  pippin:   ["lorc/crystal-ball",      "Lorc",       "Crystal ball"],
  gandalf:  ["lorc/pointy-hat",        "Lorc",       "Pointy hat"],
  aragorn:  ["lorc/rune-sword",        "Lorc",       "Rune sword"],
  legolas:  ["delapouite/bow-arrow",   "Delapouite", "Bow arrow"],
  gimli:    ["lorc/battle-axe",        "Lorc",       "Battle axe"],
  boromir:  ["delapouite/mighty-horn", "Delapouite", "Mighty horn"],
  bilbo:    ["delapouite/smoking-pipe","Delapouite", "Smoking pipe"],
  gollum:   ["lorc/frog",              "Lorc",       "Frog"],
  saruman:  ["lorc/wizard-staff",      "Lorc",       "Wizard staff"],
  sauron:   ["lorc/burning-eye",       "Lorc",       "Burning eye"],
  theoden:  ["lorc/horse-head",        "Lorc",       "Horse head"],
  eowyn:    ["cathelineau/swordwoman", "Cathelineau","Swordwoman"],
  faramir:  ["lorc/white-tower",       "Lorc",       "White tower"],
  treebeard:["lorc/ent-mouth",         "Lorc",       "Ent mouth"],
  thorin:   ["kier-heyl/dwarf-king",   "Kier Heyl",  "Dwarf king"],
  smaug:    ["lorc/dragon-head",       "Lorc",       "Dragon head"],
};

const BASE = "https://raw.githubusercontent.com/game-icons/icons/master/";
const OUT_SVG_DIR = "/Users/mi-shn001/dev/lotr/assets/icons/";
const OUT_JS = "/Users/mi-shn001/dev/lotr/js/icons.js";

await mkdir(OUT_SVG_DIR, { recursive: true });

const entries = [];
for (const [char, [path, author, title]] of Object.entries(ICONS)) {
  const res = await fetch(BASE + path + ".svg");
  if (!res.ok) throw new Error(`${path}: HTTP ${res.status}`);
  const svg = await res.text();
  await writeFile(OUT_SVG_DIR + char + ".svg", svg);

  const viewBox = (svg.match(/viewBox="([^"]+)"/) || [])[1] || "0 0 512 512";
  const paths = [...svg.matchAll(/<path\s[^>]*d="([^"]+)"/g)]
    .map((m) => m[1])
    .filter((d) => !/^M0 0h512v512H0z$/i.test(d)); // drop background square
  if (!paths.length) throw new Error(`${path}: no path data found`);
  entries.push({ char, paths, viewBox, author, title });
  console.log(`${char}: ${path} (${paths.length} path(s), viewBox ${viewBox})`);
}

let js = `/* ============================================================
 * icons.js — GENERATED by build-icons.mjs. Do not edit by hand.
 * Character glyphs from game-icons.net, CC BY 3.0
 * (https://creativecommons.org/licenses/by/3.0/).
 * Authors per icon are noted below and credited in the README.
 * ============================================================ */

const CHAR_ICONS = {
`;
for (const e of entries) {
  js += `  // "${e.title}" by ${e.author}\n`;
  js += `  ${e.char}: { viewBox: "${e.viewBox}", paths: ${JSON.stringify(e.paths)} },\n`;
}
js += `};\n`;
await writeFile(OUT_JS, js);
console.log(`\nWrote ${OUT_JS} (${entries.length} icons)`);
